// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiceOrders.Infrastructure.Persistence;

#nullable disable

namespace ServiceOrders.Infrastructure.Migrations
{
    [DbContext(typeof(ServiceOrdersDbContext))]
    partial class ServiceOrdersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ServiceOrders.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("ServiceOrders.Domain.Entities.ChecklistResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChecklistTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("OrderOfServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistTemplateId");

                    b.HasIndex("OrderOfServiceId")
                        .IsUnique();

                    b.ToTable("ChecklistResponses");
                });

            modelBuilder.Entity("ServiceOrders.Domain.Entities.ChecklistResponseItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChecklistResponseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChecklistTemplateItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomInputPayload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observation")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistResponseId");

                    b.HasIndex("ChecklistTemplateItemId");

                    b.ToTable("ChecklistResponseItems");
                });

            modelBuilder.Entity("ServiceOrders.Domain.Entities.ChecklistTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("PublishedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("ChecklistTemplates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f0d2fb49-7b89-42cc-9e6b-5f2f0e57291b"),
                            IsPublished = true,
                            PublishedBy = "engenharia@serviceorders.local",
                            Title = "Checklist Veicular - v1",
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("ServiceOrders.Domain.Entities.ChecklistTemplateItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChecklistTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CustomInputComponentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DefaultOutcome")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("HasCustomInput")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistTemplateId");

                    b.HasIndex("CustomInputComponentId");

                    b.ToTable("ChecklistTemplateItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d2ccf0a2-49b9-4d3f-97a7-a1a2d1bdc1d5"),
                            ChecklistTemplateId = new Guid("f0d2fb49-7b89-42cc-9e6b-5f2f0e57291b"),
                            DefaultOutcome = "Approved",
                            Description = "Inspeção visual da carroceria",
                            DisplayOrder = 0,
                            HasCustomInput = false
                        },
                        new
                        {
                            Id = new Guid("a7c75cf0-7016-4d72-9e76-4e927c6de7a8"),
                            ChecklistTemplateId = new Guid("f0d2fb49-7b89-42cc-9e6b-5f2f0e57291b"),
                            CustomInputComponentId = new Guid("a3137f9c-6126-4bf4-9dd4-1f3d9cb1aa10"),
                            DefaultOutcome = "Approved",
                            Description = "Registrar dados do veículo",
                            DisplayOrder = 1,
                            HasCustomInput = true
                        });
                });

            modelBuilder.Entity("ServiceOrders.Domain.Entities.CustomInputComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("JsonBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("CustomInputComponents");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a3137f9c-6126-4bf4-9dd4-1f3d9cb1aa10"),
                            JsonBody = "{\n  \"fields\": [\n    { \"name\": \"placa\", \"label\": \"Placa\", \"type\": \"text\", \"required\": true },\n    { \"name\": \"chassi\", \"label\": \"Chassi\", \"type\": \"text\", \"required\": true },\n    { \"name\": \"modelo\", \"label\": \"Modelo\", \"type\": \"text\", \"required\": true },\n    { \"name\": \"ano\", \"label\": \"Ano\", \"type\": \"number\", \"required\": true }\n  ]\n}",
                            Name = "DadosCarro",
                            UpdatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("ServiceOrders.Domain.Entities.MonthlyTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("TargetEntries")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Year", "Month")
                        .IsUnique();

                    b.ToTable("MonthlyTargets");
                });

            modelBuilder.Entity("ServiceOrders.Domain.Entities.OrderOfService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssignedTechnician")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("ChecklistResponseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClosingNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("RejectedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("OrdersOfService");
                });

            modelBuilder.Entity("ServiceOrders.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens", (string)null);
                });

            modelBuilder.Entity("ServiceOrders.Domain.Entities.PhotoAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChecklistResponseItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("OrderOfServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistResponseItemId");

                    b.HasIndex("OrderOfServiceId");

                    b.ToTable("PhotoAttachments");
                });

            modelBuilder.Entity("ServiceOrders.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8a2c929f-3a3f-4f67-9d92-56977d042793"),
                            CreatedAt = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "admin@serviceorders.local",
                            IsActive = true,
                            Name = "Administrador OS",
                            PasswordHash = "100000.YIbxL2Hjg2HsztaG1d2ZsQ==.aQ9YkZB0C63nQtw4LHZy8pqhQMR+fb68TyK3En1XagA=",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("ServiceOrders.Domain.Entities.ChecklistResponse", b =>
                {
                    b.HasOne("ServiceOrders.Domain.Entities.ChecklistTemplate", "ChecklistTemplate")
                        .WithMany()
                        .HasForeignKey("ChecklistTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceOrders.Domain.Entities.OrderOfService", "OrderOfService")
                        .WithOne("ChecklistResponse")
                        .HasForeignKey("ServiceOrders.Domain.Entities.ChecklistResponse", "OrderOfServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChecklistTemplate");

                    b.Navigation("OrderOfService");
                });

            modelBuilder.Entity("ServiceOrders.Domain.Entities.ChecklistResponseItem", b =>
                {
                    b.HasOne("ServiceOrders.Domain.Entities.ChecklistResponse", "ChecklistResponse")
                        .WithMany("Items")
                        .HasForeignKey("ChecklistResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceOrders.Domain.Entities.ChecklistTemplateItem", "ChecklistTemplateItem")
                        .WithMany()
                        .HasForeignKey("ChecklistTemplateItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChecklistResponse");

                    b.Navigation("ChecklistTemplateItem");
                });

            modelBuilder.Entity("ServiceOrders.Domain.Entities.ChecklistTemplateItem", b =>
                {
                    b.HasOne("ServiceOrders.Domain.Entities.ChecklistTemplate", "ChecklistTemplate")
                        .WithMany("Items")
                        .HasForeignKey("ChecklistTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceOrders.Domain.Entities.CustomInputComponent", "CustomInputComponent")
                        .WithMany()
                        .HasForeignKey("CustomInputComponentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ChecklistTemplate");

                    b.Navigation("CustomInputComponent");
                });

            modelBuilder.Entity("ServiceOrders.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("ServiceOrders.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ServiceOrders.Domain.Entities.PhotoAttachment", b =>
                {
                    b.HasOne("ServiceOrders.Domain.Entities.ChecklistResponseItem", "ChecklistResponseItem")
                        .WithMany("Attachments")
                        .HasForeignKey("ChecklistResponseItemId");

                    b.HasOne("ServiceOrders.Domain.Entities.OrderOfService", "OrderOfService")
                        .WithMany("Attachments")
                        .HasForeignKey("OrderOfServiceId");

                    b.Navigation("ChecklistResponseItem");

                    b.Navigation("OrderOfService");
                });

            modelBuilder.Entity("ServiceOrders.Domain.Entities.ChecklistResponse", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ServiceOrders.Domain.Entities.ChecklistResponseItem", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("ServiceOrders.Domain.Entities.ChecklistTemplate", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ServiceOrders.Domain.Entities.OrderOfService", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("ChecklistResponse");
                });
#pragma warning restore 612, 618
        }
    }
}
